version: '3'

services:
  project:
    restart: always
    build:
      context: ./src
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    restart: always
    build:
      context: ./pgdump
      dockerfile: dockerfile_pg
    volumes:
      - ./pgdump/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: "password"
  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: dockerfile.nginx.prod
    depends_on:
      - project
    volumes:
      - ./src/project/static:/var/www/static
    ports:
      - '8088:80'
      - '5443:443'